apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-state-metrics
  namespace: argo-cd
spec:
  generators:
    - git:
        repoURL: https://github.com/fsstack/argocd-sandbox.git
        revision: HEAD
        files:
          - path: "cluster-config/**/config.json"
  template:
    metadata:
      name: "{{cluster.name}}-kube-state-metrics"
      namespace: argo-cd
    spec:
      project: default
      source:
        repoURL: https://prometheus-community.github.io/helm-charts
        chart: kube-state-metrics
        targetRevision: 4.7.0
        helm:
          values: |
            prometheus:
              monitor:
                enabled: true
      destination:
        server: "{{cluster.server}}"
        namespace: kube-state-metrics
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
