apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus-primary
  namespace: argo-cd
spec:
  generators:
    - git:
        repoURL: https://github.com/fsstack/argocd-sandbox.git
        revision: HEAD
        files:
          - path: "cluster-config/**/config.json"
  template:
    metadata:
      name: "{{cluster.name}}-prometheus-primary"
      namespace: argo-cd
    spec:
      project: default
      source:
        repoURL: https://github.com/fsstack/argocd-sandbox.git
        path: addons/prometheus-primary
      destination:
        server: "{{cluster.server}}"
        namespace: prometheus-primary
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
