apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus-operator
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{name}}-prometheus-operator"
      namespace: argo-cd
    spec:
      project: default
      source:
        repoURL: https://github.com/fsstack/argocd-sandbox.git
        path: addons/prometheus-operator-v0.49.0
      destination:
        server: "{{server}}"
        namespace: prometheus-operator
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: node-exporter
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{name}}-node-exporter"
      namespace: argo-cd
    spec:
      project: default
      source:
        repoURL: https://prometheus-community.github.io/helm-charts
        chart: prometheus-node-exporter
        targetRevision: 3.2.0
      destination:
        server: "{{server}}"
        namespace: node-exporter
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
